### PR TITLE
Typo fix in padr error message for rows returned

### PR DESCRIPTION
**Pull request by sharlagelfand**
milion --> million

### CODE REVIEW

**Comment by sharlagelfand** [comment]
although now that i'm looking further, i think it should return the original `threshold` million, instead of the version that is derived just before this message is returned -- e.g. if `break_above = 1`, then `threshold = 10 ^ 6`, and the error should read "... larger than 10 ^ 6 in break_above" OR "... larger than 1 million in break_above", but not "... larger than 10 ^ 6 million"

let me know what you think and I'll edit the PR!

**Comment by EdwinTh** [comment]
Thanks! I sincerely did not know it was with double "l", learned something new here :) Will check documentation as well. And indeed the line that updates the threshold is redundant, sharp!

**Comment by sharlagelfand** [comment]
from what I could see, the rest of the documentation is good to go! it only appears otherwise when describing the `break_above` argument in `pad()`, where you use "millions" :)

**Comment by EdwinTh** [comment]
Spell check probably caught that one :). Will merge soon and remove the redundant update.

**Pull request merged**
