### PR TITLE
fixes pad to return data.frame

### PR DESCRIPTION
**Pull request by kevinykuo**

### CODE REVIEW

**Comment by EdwinTh** [comment]
Yes, the printing is temporary placeholder. It of course needs to return a data.frame again. However I would like to do the printing of the message below the returned frame so it won't be missed. This will not give that, still need to figure out how to implement that.

**Comment by kevinykuo** [comment]
You might have considered this but here's one approach. Alternatively we can use `warning()`?

**Comment by EdwinTh** [comment]
That's indeed something I am considering, but I am not keen on adding a class. I would like to keep things as clean (or tidy) as possible. Thanks for the implementation, I still might go with this option if I don't find an alternative.

**Comment by kevinykuo** [comment]
Yeah this is kinda hack-y and I can see it breaking other stuff. I'd be interested to see what you come up with!

**Comment by EdwinTh** [comment]
Me too :). Thanks anyway for your effort, made some things a bit more clear to me.

**Pull request closed without merging**
